version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-alpine
    container_name: cyberscan-rabbitmq
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]
    expose:
      - '5672'

  db:
    image: postgres:11-alpine
    restart: always
    container_name: cyberscan-postgres
    environment:
      - POSTGRES_DB=patrowl_db
      - POSTGRES_USER=PATROWL_DB_USER
      - POSTGRES_PASSWORD=PATROWL_DB_PASSWD_TO_CHANGE
    expose:
      - '5432'
    volumes:
      - ./var/db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    #   - ./pg_data:/var/lib/postgresql/data/

  web:
    container_name: cyberscan-frontend
    build: .
    image: cyberscan-frontend:latest
    environment:
      - POSTGRES_HOST=db
      - DEBUG=True
      - RABBITMQ_HOSTNAME=rabbitmq:5672
    depends_on:
      - db
      - rabbitmq
    expose:
      - "8003"
    volumes:
      - ./staticfiles:/opt/cyberscan-frontend/staticfiles
      - ./media:/opt/cyberscan-frontend/media
    links:
      - db
      - rabbitmq

  nginx:
    image: nginx:stable-alpine
    container_name: cyberscan-nginx
    ports:
      - "8083:8083"
    volumes:
      - ./staticfiles:/opt/cyberscan-frontend/staticfiles
      # - ./media:/opt/cyberscan-frontend/media
      - ./var/log:/opt/cyberscan-frontend/var/log
      - ./nginx_docker.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
